
###
GET http://localhost:5500/api/users/overview

###
GET http://localhost:5500/api/users/all-debtors

###
GET http://localhost:5500/api/users/all-agents

###
GET http://localhost:5500/api/users/agent/69fe03b349a51528ed29c28f

###
DELETE http://localhost:5500/api/users/agent/6a04cb76f75cd493ce5e4ea8

###
GET http://localhost:5500/api/debts





###
POST http://localhost:5500/admin/add-agent
Content-Type: application/json

{
  "fullName": "Meshack Makumbane",
  "phoneNumber": "0768831563",
  "email": "meshanele19@gmail.com"
}

###
GET http://localhost:5500/admin/get-agents

###
POST http://localhost:5500/admin/add-debtor
Content-Type: application/json

{
  "fullName": "Meshack Makumbane",
  "phoneNumber": "0768831563",
  "email": "meshanele19@gmail.com",
  "idNumber": "1234567890123",
  "balance": 76764787
}

###
GET http://localhost:5500/api/users/overview


###
POST http://localhost:5500/admin/seed-admin
Content-Type: application/json

{
  "fullName": "Ayanda Zulu",
  "phoneNumber": "0123456789",
  "email": "ayanda.zulu@gmail.com"
}

###
POST http://localhost:5500/api/auth/login
Content-Type: application/json

{
  "accessId": "DH892193",
  "password": "DH463724"
}

###
GET http://localhost:5500/api/auth/profile


###
GET http://localhost:5500/api/auth/logout















###
GET http://localhost:5500/api/users/debtor/69fc9f3cbfc4b59e20ccd214

###
DELETE http://localhost:5500/api/users/debtor/6a04c132d8e9c21d475f6f15

###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
  "idNumber": "1234567890123",
  "refNumber": "REF409851"
}

###
GET http://localhost:5500/api/users/debts


###
GET http://localhost:5500/api/users/debts


### Agent login
POST http://localhost:5500/api/auth/login
Content-Type: application/json

{
  "accessId": "DH722113",
  "password": "DH663554"
}



###
POST http://localhost:5500/api/users/tickets
Content-Type: application/json

{
  "subject": "The issues with Meshack is fixed, thanks",
  "priority": "low",
  "description" :"I wont be proceeding with anything, he paid R2000"
}





###
GET http://localhost:5500/api/users/tickets


###
POST http://localhost:5500/api/users/ticket/6a05b63b5baa257c908061cc
Content-Type: application/json

{
  "description" :"it seems there was a problem"
}

###
GET http://localhost:5500/api/users/notifications